# -*- coding: utf-8 -*-
"""AI interview analyser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1udGdT9DO6r4VgDfI8k3Vd8pNuTD5YYbn
"""

import kagglehub
import os
import re
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.ensemble import RandomForestRegressor
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('stopwords')
from sentence_transformers import (SentenceTransformer)
stop_words = set(stopwords.words('english'))
required = [
    "punkt",
    "stopwords",
    "wordnet",
    "omw-1.4"
]

for package in required:
    nltk.download(package, quiet=True)



lemmatizer = WordNetLemmatizer()

def clean_text(text):

    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r'http\S+|www\S+','',text)
    text = re.sub(r'[^a-zA-Z0-9\s]','',text)
    text = re.sub(r'\s+',' ',text)
    return text.strip()


def remove_stopwords(tokens):
    return [
        word
        for word in tokens
        if word not in stop_words
    ]
def lemmatize_words(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]






path = kagglehub.dataset_download("aryan208/hr-interview-questions-and-ideal-answers")
json_file = os.path.join(path,"hr_interview_questions_dataset.json")
df = pd.read_json(json_file)
df = df[["question","ideal_answer"]] 
df["clean_answer"] = (df["ideal_answer"].apply(clean_text))
df["tokens"] = (df["clean_answer"].apply(word_tokenize))
df["filtered_tokens"] = (df["tokens"].apply(remove_stopwords))
df["lemmatized"] = (df["filtered_tokens"].apply(lemmatize_words))
df["final_text"] = (df["lemmatized"].apply(lambda x: " ".join(x)))





model = SentenceTransformer("paraphrase-MiniLM-L6-v2")
ideal = """
Machine Learning is a subset
of AI that learns from data.
"""
user = """
ML allows computers
to learn patterns from data.
"""
emb1 = model.encode(ideal)
emb2 = model.encode(user)

score = cosine_similarity([emb1],[emb2])





print(df.head())
print(df.columns)
print(df.columns)
print("Dataset Path:", path)
print(df.head())
print(df[["question","final_text"]].head())
print("Similarity Score:",score[0][0])


df.to_csv("cleaned_interview_dataset.csv",index=False)
print("Dataset Saved")






